<?php
$title = 'Add new project';
$this->headTitle($title);
print $this->showMessages();
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('project', array('action' => 'add')));
$form->prepare();


echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<div><?php print $this->formRow($form->get('title')); ?></div>
<div><?php print $this->formRow($form->get('text')); ?></div>
<div><?php print $this->formRow($form->get('state')); ?></div>
<div><?php print $this->formSubmit($form->get('submit')); ?></div>
<?php print $this->form()->closeTag(); ?>
